### ISSUE TITLE
repeat-calling errors in nanopore sequencing of telomeres

### ISSUE THREAD

**Issue by Kmanjor** [zstephens/telogator#1]
Hi,

Thanks for your telogator. 

I noticed a paper recently published entitled 'Identifying and correcting repeat-calling errors in nanopore sequencing of telomeres (https://www.biorxiv.org/content/10.1101/2022.01.11.475254v1)' in bioRxiv.

It mentioned that telomeres which are represented by (TTAGGG)n and (CCCTAA)n repeats in many organisms were frequently miscalled (~40-50% of reads) as (TTAAAA)n, or as (CTTCTT)n and (CCCTGG)n repeats respectively in a strand-specific manner during nanopore sequencing.

I found that your script 'tg_kmer.py' contained TEL_KMERS_P  and TEL_KMERS_Q.  I understand your telogator is designed for PacBio first.

Could you refer to the article above, and give some suggestion using telogator for nanopore?

Thank you very much!

Best

Tong

**Comment by zstephens** [comment]
Greetings Tong,

Thanks for bringing this paper to my attention, this is very interesting! I think the best route forward would be to provide more flexibility to users for which kmers to use instead of hardcoding them in tg_kmer.py. I will spend some time reading through this paper more thoroughly, and I will add input options so that nanopore data can be better accommodated.

Thanks!
Zach

**Comment by Kmanjor** [comment]
您好，我是李桐，已收到您的邮件，祝您天天开心，工作愉快。This is an automatic reply, confirming that your e-mail was received. Thank you.

**Comment by zstephens** [comment]
I added support for user-specified kmer lists in 38c32ba using the -k input option. I also added a nanopore_kmers.tsv file containing additional kmers as described in the paper.

Thanks again for bringing this to my attention!
