### ISSUE TITLE
Advice optimizing Telogator

### ISSUE THREAD

**Issue by niyati1211** [zstephens/telogator#14]
I am considering applying to Telogator to analyze long-read WGS data (PacBio SMRT technology). The dataset I am working with includes long-read WGS for ~1000 individuals (FASTA files). Most of the samples have mean coverage of ~8x, and the median read length for each sample ranges from 13kb to 21kb (10kb read length was the minimum to be included). 
From the Telogator paper, it seems that at 8x coverage, we may be at the boundary of being able to sufficiently estimate telomere length for all chromosome arms. Do you have any guidance on how best to optimize the method?

**Comment by zstephens** [comment]
Greetings! If you're working with HiFi data I highly recommend using our updated software Telogator2, found [here](https://github.com/zstephens/telogator2). The only reason to use Telogator1 at this point is if you are using very noisy CLR reads, which aren't supported by Telogator2.

With Telogator2 there are a few parameters that can be reduced in order to report telomeres even if they're only supported by 1 or 2 reads (using input options `-n 1` or `-n 2`), though with these reduced thresholds there will inevitably be some false positives.

**Comment by niyati1211** [comment]
Thank you so much for the quick response! That makes sense, I will use Telogator2 then.

**Comment by zstephens** [comment]
Sounds great! Feel free to open an issue in that repository if you run into any problems or have questions about interpreting results.
