### ISSUE TITLE
telogator is also useful for CCS reads? 

### ISSUE THREAD

**Issue by AhmedArslan** [zstephens/telogator#4]
Hi,
I want to know if telogator is also useful for CCS reads? 
Thanks.
Ahmed.

**Comment by zstephens** [comment]
Indeed! The only differences would be in the alignment parameters (e.g. using pbmm2 with `--preset CCS` or minimap2 with `-ax map-hifi`, instead of their subread settings). If the coverage of your data is particularly low it might be worth reducing the stringency of some filtering parameters, e.g. the `-cr` parameter for merge_jobs.py specifying the minimum number of reads required to report a subtelomere/telomere boundary.

**Comment by AhmedArslan** [comment]
Thank you, another point is related to the reference genome:
1 - T2T has a new version out, v2, can I use v2?
2 - hg38/GRCh38, can also be useful?

**Comment by zstephens** [comment]
I recently updated Telogator to support chrY which is now included with T2T v2, so that's definitely the version of the reference I recommend using (I should update the readme to reflect this if I haven't already).

I don't recommend using hg38 as most of its subtelomeres are poorly characterized (they often contain large blocks of Ns, or are very structurally dissimilar to the subtelomeres we observed in our samples)
