### ISSUE TITLE
Error Message at Telogator v2.0 Step 5

### ISSUE THREAD

**Issue by yuxinnnnnn** [zstephens/telogator#9]
Hi,

I am currently trying the Telogator v2.0. However, I got this message during step 5:
```
python3 ~/scratch/telogator_v2.0/telogator/telogator.py -i subtel_aln-01.bam -o telogator_out-01/ --debug
using default telomere kmers
getting all read data from input alignment...Traceback (most recent call last):
  File "/home/user/scratch/telogator_v2.0/telogator/telogator.py", line 493, in <module>
    main()
  File "/home/user/scratch/telogator_v2.0/telogator/telogator.py", line 180, in main
    sam_line[2] = refseqs[int(sam_line[2])]	# pysam is dumb and prints ref indices instead of contig name
ValueError: invalid literal for int() with base 10: '#0'
```

The Tegogator 1.0 worked for this step.

Could you provide any insight? Thanks!

**Comment by zstephens** [comment]
Greetings, I'm not quite sure why the ref index field returned by pysam would ever contain a # character. I pushed a quick update to remove such characters (commit: f749fd988258e90f27548d7ad1d80551b119e441), but I'm not super happy that I don't know yet know what the underlying issue is. Could you rerun your bam through with the latest commit and let me know if the results look sensible?

Thanks!

**Comment by yuxinnnnnn** [comment]
I just pull the latest commit.
But getting something similar:

```
using default telomere kmers
getting all read data from input alignment...Traceback (most recent call last):
  File "/home/user/scratch/telogator_v2.0/telogator/telogator.py", line 496, in <module>
    main()
  File "/home/user/scratch/telogator_v2.0/telogator/telogator.py", line 181, in main
    sam_line[2] = refseqs[int(my_ref_ind)]		# pysam is dumb and prints ref indices instead of contig name
ValueError: invalid literal for int() with base 10: '*'
```

Trying with another bam file also lead me to this message..

**Comment by zstephens** [comment]
It looks like I was not handling unmapped reads correctly (the bams I was using to test the updates didn't contain any unmapped reads, so I missed this). I added some additional checks to properly filter these out in commit 12389f50e61504c9304d51d088732a58f3006943, hopefully it will run now (or at least make it further in before finding something else I need to fix, thanks for your patience! :))

**Comment by yuxinnnnnn** [comment]
No problem! And thank you for explaining the issue! 
I got my violin plots, and they are sighly different. Is that expected?

tlens plot produced my Telogator 1.0:
![tlens_violin_03_all-pass](https://user-images.githubusercontent.com/74065049/204335173-a0b3d113-ee42-48a4-86ad-bb7e3637e645.png)

tlens plot produced my Telogator 2.0:
![violin_tlens](https://user-images.githubusercontent.com/74065049/204335073-4c0b989c-403e-4be7-a802-3167da705f99.png)

And the results tlens.tsv for both Telogator 1.0 and 2.0, I got two `15p` estimated length reported. Would you know why this happened?

tlens tsv produced my Telogator 1.0:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/74065049/204335983-647c294c-2fad-4a0f-85b8-9fdd41cf2780.png">

tlens plot produced my Telogator 2.0:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/74065049/204336040-9b70a4c5-0816-49b1-bd5d-8da9e892d911.png">

Thanks!

**Comment by zstephens** [comment]
Some minor differences should be expected, mostly due to changes in the set of kmers that telogator looks for when determining if a region is a telomere or not. Essentially for telogator v1 the set of kmers was chosen from analyzing a couple samples and seeing what their telomeres looked like, whereas the set in v2 was derived from a much larger collection of samples and should be a bit more comprehensive (though as you can see the effect isn't dramatic).

For the two clusters on chr15p, it looks like there are 6 reads anchored to position 3601 and another 6 reads anchored to 6076. It's possible that these represent the two alleles of chr15p, e.g. one allele has a TL of ~6k and the other has ~11k. (It's also possible that one of the clusters *actually* originated from an arm other than 15p, but determining that specifically is something that will have to wait for telogator v3).

**Comment by yuxinnnnnn** [comment]
Thanks for the explaination!
What do you mean by "v2 was derived from a much larger collection of samples"?

I have ran both Telogators on the same 3 persons, this is what I got:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/74065049/204393552-41cd1ca8-d80f-4c56-a6f3-d736297c4237.png">

I realized that chromosome 9 seems to be "excluded", and v1 seems to have more telomere reported (in terms of the chromosome arm)? But I am trying on more data.

**Comment by zstephens** [comment]
What kind of reads are you using? The default parameters for Telogator v1 were geared towards noisy long reads (e.g. PacBio CLR or earlier Nanopore protocols), but in v2 I raised a few thresholds to reduce false positives and shifted the defaults towards values more appropriate for PacBio HiFi reads, or Nanopore Q20 reads. Using the input option `-r ont` or `-r clr` will use the same thresholds as Telogator v1, and will likely result in more reads making it to the final steps (though the results may be a bit less trustworthy). Either way, the results definitely look similar between the two versions, and in general I would be less trusting of chromosome arms that have only a small number of reads.

As for the kmers, previously the set we were using was derived from a manual analysis of the T2T reference genome. in v2 the set of kmers was derived from (again, a largely manual) analysis of ~50 genome assemblies that were publicly available from the Human Pangenome Project.

**Comment by yuxinnnnnn** [comment]
Hi, sorry for my late reply!
To answer your question, I am using the PabBio Hifi reads. So if I understand well, the result that I got make sence since you raised some thresholds?

Thanks!
